version: "3.8"
services:
    backend:
        container_name: "backend-app"
        restart: unless-stopped
        build:
            context: ./backend
        ports:
            - "6709:6709"
    frontend:
        container_name: "frontend-app"
        restart: always
        build:
            context: ./frontend
        ports:
            - "80:80"